/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCursosRouteImport } from './routes/_authenticated/cursos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedMinhaTrilhaRouteImport } from './routes/_authenticated/minha-trilha'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAdminArquivosRouteImport } from './routes/_authenticated/admin/arquivos'
import { Route as AuthenticatedAdminAulasRouteImport } from './routes/_authenticated/admin/aulas'
import { Route as AuthenticatedAdminCursosRouteImport } from './routes/_authenticated/admin/cursos'
import { Route as AuthenticatedAdminModulosRouteImport } from './routes/_authenticated/admin/modulos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAulaLessonIdRouteImport } from './routes/_authenticated/aula.$lessonId'
import { Route as AuthenticatedCursoCourseIdRouteImport } from './routes/_authenticated/curso.$courseId'
import { Route as AuthenticatedAdminAulasLessonIdRouteImport } from './routes/_authenticated/admin/aulas.$lessonId'
import { Route as AuthenticatedAdminCursosCourseIdRouteImport } from './routes/_authenticated/admin/cursos.$courseId'
import { Route as AuthenticatedAdminModulosModuleIdRouteImport } from './routes/_authenticated/admin/modulos.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursosRoute = AuthenticatedCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaTrilhaRoute =
  AuthenticatedMinhaTrilhaRouteImport.update({
    id: '/minha-trilha',
    path: '/minha-trilha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminArquivosRoute =
  AuthenticatedAdminArquivosRouteImport.update({
    id: '/arquivos',
    path: '/arquivos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAulasRoute = AuthenticatedAdminAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCursosRoute =
  AuthenticatedAdminCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulosRoute =
  AuthenticatedAdminModulosRouteImport.update({
    id: '/modulos',
    path: '/modulos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAulaLessonIdRoute =
  AuthenticatedAulaLessonIdRouteImport.update({
    id: '/aula/$lessonId',
    path: '/aula/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursoCourseIdRoute =
  AuthenticatedCursoCourseIdRouteImport.update({
    id: '/curso/$courseId',
    path: '/curso/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAulasLessonIdRoute =
  AuthenticatedAdminAulasLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AuthenticatedAdminAulasRoute,
  } as any)
const AuthenticatedAdminCursosCourseIdRoute =
  AuthenticatedAdminCursosCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminCursosRoute,
  } as any)
const AuthenticatedAdminModulosModuleIdRoute =
  AuthenticatedAdminModulosModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedAdminModulosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/cursos': typeof AuthenticatedCursosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/minha-trilha': typeof AuthenticatedMinhaTrilhaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/arquivos': typeof AuthenticatedAdminArquivosRoute
  '/admin/aulas': typeof AuthenticatedAdminAulasRouteWithChildren
  '/admin/cursos': typeof AuthenticatedAdminCursosRouteWithChildren
  '/admin/modulos': typeof AuthenticatedAdminModulosRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/curso/$courseId': typeof AuthenticatedCursoCourseIdRoute
  '/admin/aulas/$lessonId': typeof AuthenticatedAdminAulasLessonIdRoute
  '/admin/cursos/$courseId': typeof AuthenticatedAdminCursosCourseIdRoute
  '/admin/modulos/$moduleId': typeof AuthenticatedAdminModulosModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/cursos': typeof AuthenticatedCursosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/minha-trilha': typeof AuthenticatedMinhaTrilhaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/arquivos': typeof AuthenticatedAdminArquivosRoute
  '/admin/aulas': typeof AuthenticatedAdminAulasRouteWithChildren
  '/admin/cursos': typeof AuthenticatedAdminCursosRouteWithChildren
  '/admin/modulos': typeof AuthenticatedAdminModulosRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/curso/$courseId': typeof AuthenticatedCursoCourseIdRoute
  '/admin/aulas/$lessonId': typeof AuthenticatedAdminAulasLessonIdRoute
  '/admin/cursos/$courseId': typeof AuthenticatedAdminCursosCourseIdRoute
  '/admin/modulos/$moduleId': typeof AuthenticatedAdminModulosModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/cursos': typeof AuthenticatedCursosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/minha-trilha': typeof AuthenticatedMinhaTrilhaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/arquivos': typeof AuthenticatedAdminArquivosRoute
  '/_authenticated/admin/aulas': typeof AuthenticatedAdminAulasRouteWithChildren
  '/_authenticated/admin/cursos': typeof AuthenticatedAdminCursosRouteWithChildren
  '/_authenticated/admin/modulos': typeof AuthenticatedAdminModulosRouteWithChildren
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/_authenticated/curso/$courseId': typeof AuthenticatedCursoCourseIdRoute
  '/_authenticated/admin/aulas/$lessonId': typeof AuthenticatedAdminAulasLessonIdRoute
  '/_authenticated/admin/cursos/$courseId': typeof AuthenticatedAdminCursosCourseIdRoute
  '/_authenticated/admin/modulos/$moduleId': typeof AuthenticatedAdminModulosModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/cursos'
    | '/dashboard'
    | '/materiais'
    | '/minha-trilha'
    | '/perfil'
    | '/admin/arquivos'
    | '/admin/aulas'
    | '/admin/cursos'
    | '/admin/modulos'
    | '/admin/usuarios'
    | '/aula/$lessonId'
    | '/curso/$courseId'
    | '/admin/aulas/$lessonId'
    | '/admin/cursos/$courseId'
    | '/admin/modulos/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/cursos'
    | '/dashboard'
    | '/materiais'
    | '/minha-trilha'
    | '/perfil'
    | '/admin/arquivos'
    | '/admin/aulas'
    | '/admin/cursos'
    | '/admin/modulos'
    | '/admin/usuarios'
    | '/aula/$lessonId'
    | '/curso/$courseId'
    | '/admin/aulas/$lessonId'
    | '/admin/cursos/$courseId'
    | '/admin/modulos/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/cursos'
    | '/_authenticated/dashboard'
    | '/_authenticated/materiais'
    | '/_authenticated/minha-trilha'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/arquivos'
    | '/_authenticated/admin/aulas'
    | '/_authenticated/admin/cursos'
    | '/_authenticated/admin/modulos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/aula/$lessonId'
    | '/_authenticated/curso/$courseId'
    | '/_authenticated/admin/aulas/$lessonId'
    | '/_authenticated/admin/cursos/$courseId'
    | '/_authenticated/admin/modulos/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos': {
      id: '/_authenticated/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof AuthenticatedCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-trilha': {
      id: '/_authenticated/minha-trilha'
      path: '/minha-trilha'
      fullPath: '/minha-trilha'
      preLoaderRoute: typeof AuthenticatedMinhaTrilhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/arquivos': {
      id: '/_authenticated/admin/arquivos'
      path: '/arquivos'
      fullPath: '/admin/arquivos'
      preLoaderRoute: typeof AuthenticatedAdminArquivosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/aulas': {
      id: '/_authenticated/admin/aulas'
      path: '/aulas'
      fullPath: '/admin/aulas'
      preLoaderRoute: typeof AuthenticatedAdminAulasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cursos': {
      id: '/_authenticated/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AuthenticatedAdminCursosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modulos': {
      id: '/_authenticated/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AuthenticatedAdminModulosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/aula/$lessonId': {
      id: '/_authenticated/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/aula/$lessonId'
      preLoaderRoute: typeof AuthenticatedAulaLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/$courseId': {
      id: '/_authenticated/curso/$courseId'
      path: '/curso/$courseId'
      fullPath: '/curso/$courseId'
      preLoaderRoute: typeof AuthenticatedCursoCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/aulas/$lessonId': {
      id: '/_authenticated/admin/aulas/$lessonId'
      path: '/$lessonId'
      fullPath: '/admin/aulas/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminAulasLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminAulasRoute
    }
    '/_authenticated/admin/cursos/$courseId': {
      id: '/_authenticated/admin/cursos/$courseId'
      path: '/$courseId'
      fullPath: '/admin/cursos/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCursosCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminCursosRoute
    }
    '/_authenticated/admin/modulos/$moduleId': {
      id: '/_authenticated/admin/modulos/$moduleId'
      path: '/$moduleId'
      fullPath: '/admin/modulos/$moduleId'
      preLoaderRoute: typeof AuthenticatedAdminModulosModuleIdRouteImport
      parentRoute: typeof AuthenticatedAdminModulosRoute
    }
  }
}

interface AuthenticatedAdminAulasRouteChildren {
  AuthenticatedAdminAulasLessonIdRoute: typeof AuthenticatedAdminAulasLessonIdRoute
}

const AuthenticatedAdminAulasRouteChildren: AuthenticatedAdminAulasRouteChildren =
  {
    AuthenticatedAdminAulasLessonIdRoute: AuthenticatedAdminAulasLessonIdRoute,
  }

const AuthenticatedAdminAulasRouteWithChildren =
  AuthenticatedAdminAulasRoute._addFileChildren(
    AuthenticatedAdminAulasRouteChildren,
  )

interface AuthenticatedAdminCursosRouteChildren {
  AuthenticatedAdminCursosCourseIdRoute: typeof AuthenticatedAdminCursosCourseIdRoute
}

const AuthenticatedAdminCursosRouteChildren: AuthenticatedAdminCursosRouteChildren =
  {
    AuthenticatedAdminCursosCourseIdRoute:
      AuthenticatedAdminCursosCourseIdRoute,
  }

const AuthenticatedAdminCursosRouteWithChildren =
  AuthenticatedAdminCursosRoute._addFileChildren(
    AuthenticatedAdminCursosRouteChildren,
  )

interface AuthenticatedAdminModulosRouteChildren {
  AuthenticatedAdminModulosModuleIdRoute: typeof AuthenticatedAdminModulosModuleIdRoute
}

const AuthenticatedAdminModulosRouteChildren: AuthenticatedAdminModulosRouteChildren =
  {
    AuthenticatedAdminModulosModuleIdRoute:
      AuthenticatedAdminModulosModuleIdRoute,
  }

const AuthenticatedAdminModulosRouteWithChildren =
  AuthenticatedAdminModulosRoute._addFileChildren(
    AuthenticatedAdminModulosRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminArquivosRoute: typeof AuthenticatedAdminArquivosRoute
  AuthenticatedAdminAulasRoute: typeof AuthenticatedAdminAulasRouteWithChildren
  AuthenticatedAdminCursosRoute: typeof AuthenticatedAdminCursosRouteWithChildren
  AuthenticatedAdminModulosRoute: typeof AuthenticatedAdminModulosRouteWithChildren
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminArquivosRoute: AuthenticatedAdminArquivosRoute,
    AuthenticatedAdminAulasRoute: AuthenticatedAdminAulasRouteWithChildren,
    AuthenticatedAdminCursosRoute: AuthenticatedAdminCursosRouteWithChildren,
    AuthenticatedAdminModulosRoute: AuthenticatedAdminModulosRouteWithChildren,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCursosRoute: typeof AuthenticatedCursosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedMinhaTrilhaRoute: typeof AuthenticatedMinhaTrilhaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAulaLessonIdRoute: typeof AuthenticatedAulaLessonIdRoute
  AuthenticatedCursoCourseIdRoute: typeof AuthenticatedCursoCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCursosRoute: AuthenticatedCursosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedMinhaTrilhaRoute: AuthenticatedMinhaTrilhaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAulaLessonIdRoute: AuthenticatedAulaLessonIdRoute,
  AuthenticatedCursoCourseIdRoute: AuthenticatedCursoCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
