/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ValidarCertificadoRouteImport } from './routes/validar-certificado'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedCursosRouteImport } from './routes/_authenticated/cursos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedMinhaTrilhaRouteImport } from './routes/_authenticated/minha-trilha'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAdminArquivosRouteImport } from './routes/_authenticated/admin/arquivos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAulaLessonIdRouteImport } from './routes/_authenticated/aula.$lessonId'
import { Route as AuthenticatedAvaliacaoAssessmentIdRouteImport } from './routes/_authenticated/avaliacao.$assessmentId'
import { Route as AuthenticatedCursoCourseIdRouteImport } from './routes/_authenticated/curso.$courseId'
import { Route as AuthenticatedAdminAcompanhamentoIndexRouteImport } from './routes/_authenticated/admin/acompanhamento.index'
import { Route as AuthenticatedAdminAcompanhamentoUserIdRouteImport } from './routes/_authenticated/admin/acompanhamento.$userId'
import { Route as AuthenticatedAdminAulasIndexRouteImport } from './routes/_authenticated/admin/aulas.index'
import { Route as AuthenticatedAdminAulasLessonIdRouteImport } from './routes/_authenticated/admin/aulas.$lessonId'
import { Route as AuthenticatedAdminAvaliacoesIndexRouteImport } from './routes/_authenticated/admin/avaliacoes.index'
import { Route as AuthenticatedAdminAvaliacoesAssessmentIdRouteImport } from './routes/_authenticated/admin/avaliacoes.$assessmentId'
import { Route as AuthenticatedAdminCursosIndexRouteImport } from './routes/_authenticated/admin/cursos.index'
import { Route as AuthenticatedAdminCursosCourseIdRouteImport } from './routes/_authenticated/admin/cursos.$courseId'
import { Route as AuthenticatedAdminGruposIndexRouteImport } from './routes/_authenticated/admin/grupos.index'
import { Route as AuthenticatedAdminModulosIndexRouteImport } from './routes/_authenticated/admin/modulos.index'
import { Route as AuthenticatedAdminModulosModuleIdRouteImport } from './routes/_authenticated/admin/modulos.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarCertificadoRoute = ValidarCertificadoRouteImport.update({
  id: '/validar-certificado',
  path: '/validar-certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursosRoute = AuthenticatedCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaTrilhaRoute =
  AuthenticatedMinhaTrilhaRouteImport.update({
    id: '/minha-trilha',
    path: '/minha-trilha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminArquivosRoute =
  AuthenticatedAdminArquivosRouteImport.update({
    id: '/arquivos',
    path: '/arquivos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAulaLessonIdRoute =
  AuthenticatedAulaLessonIdRouteImport.update({
    id: '/aula/$lessonId',
    path: '/aula/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvaliacaoAssessmentIdRoute =
  AuthenticatedAvaliacaoAssessmentIdRouteImport.update({
    id: '/avaliacao/$assessmentId',
    path: '/avaliacao/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursoCourseIdRoute =
  AuthenticatedCursoCourseIdRouteImport.update({
    id: '/curso/$courseId',
    path: '/curso/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAcompanhamentoIndexRoute =
  AuthenticatedAdminAcompanhamentoIndexRouteImport.update({
    id: '/acompanhamento/',
    path: '/acompanhamento/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAcompanhamentoUserIdRoute =
  AuthenticatedAdminAcompanhamentoUserIdRouteImport.update({
    id: '/acompanhamento/$userId',
    path: '/acompanhamento/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAulasIndexRoute =
  AuthenticatedAdminAulasIndexRouteImport.update({
    id: '/aulas/',
    path: '/aulas/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAulasLessonIdRoute =
  AuthenticatedAdminAulasLessonIdRouteImport.update({
    id: '/aulas/$lessonId',
    path: '/aulas/$lessonId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAvaliacoesIndexRoute =
  AuthenticatedAdminAvaliacoesIndexRouteImport.update({
    id: '/avaliacoes/',
    path: '/avaliacoes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAvaliacoesAssessmentIdRoute =
  AuthenticatedAdminAvaliacoesAssessmentIdRouteImport.update({
    id: '/avaliacoes/$assessmentId',
    path: '/avaliacoes/$assessmentId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCursosIndexRoute =
  AuthenticatedAdminCursosIndexRouteImport.update({
    id: '/cursos/',
    path: '/cursos/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCursosCourseIdRoute =
  AuthenticatedAdminCursosCourseIdRouteImport.update({
    id: '/cursos/$courseId',
    path: '/cursos/$courseId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGruposIndexRoute =
  AuthenticatedAdminGruposIndexRouteImport.update({
    id: '/grupos/',
    path: '/grupos/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulosIndexRoute =
  AuthenticatedAdminModulosIndexRouteImport.update({
    id: '/modulos/',
    path: '/modulos/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulosModuleIdRoute =
  AuthenticatedAdminModulosModuleIdRouteImport.update({
    id: '/modulos/$moduleId',
    path: '/modulos/$moduleId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/validar-certificado': typeof ValidarCertificadoRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/minha-trilha': typeof AuthenticatedMinhaTrilhaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/arquivos': typeof AuthenticatedAdminArquivosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/avaliacao/$assessmentId': typeof AuthenticatedAvaliacaoAssessmentIdRoute
  '/curso/$courseId': typeof AuthenticatedCursoCourseIdRoute
  '/admin/acompanhamento/$userId': typeof AuthenticatedAdminAcompanhamentoUserIdRoute
  '/admin/aulas/$lessonId': typeof AuthenticatedAdminAulasLessonIdRoute
  '/admin/avaliacoes/$assessmentId': typeof AuthenticatedAdminAvaliacoesAssessmentIdRoute
  '/admin/cursos/$courseId': typeof AuthenticatedAdminCursosCourseIdRoute
  '/admin/modulos/$moduleId': typeof AuthenticatedAdminModulosModuleIdRoute
  '/admin/acompanhamento/': typeof AuthenticatedAdminAcompanhamentoIndexRoute
  '/admin/aulas/': typeof AuthenticatedAdminAulasIndexRoute
  '/admin/avaliacoes/': typeof AuthenticatedAdminAvaliacoesIndexRoute
  '/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
  '/admin/grupos/': typeof AuthenticatedAdminGruposIndexRoute
  '/admin/modulos/': typeof AuthenticatedAdminModulosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/validar-certificado': typeof ValidarCertificadoRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/minha-trilha': typeof AuthenticatedMinhaTrilhaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/arquivos': typeof AuthenticatedAdminArquivosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/avaliacao/$assessmentId': typeof AuthenticatedAvaliacaoAssessmentIdRoute
  '/curso/$courseId': typeof AuthenticatedCursoCourseIdRoute
  '/admin/acompanhamento/$userId': typeof AuthenticatedAdminAcompanhamentoUserIdRoute
  '/admin/aulas/$lessonId': typeof AuthenticatedAdminAulasLessonIdRoute
  '/admin/avaliacoes/$assessmentId': typeof AuthenticatedAdminAvaliacoesAssessmentIdRoute
  '/admin/cursos/$courseId': typeof AuthenticatedAdminCursosCourseIdRoute
  '/admin/modulos/$moduleId': typeof AuthenticatedAdminModulosModuleIdRoute
  '/admin/acompanhamento': typeof AuthenticatedAdminAcompanhamentoIndexRoute
  '/admin/aulas': typeof AuthenticatedAdminAulasIndexRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesIndexRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosIndexRoute
  '/admin/grupos': typeof AuthenticatedAdminGruposIndexRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/validar-certificado': typeof ValidarCertificadoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRoute
  '/_authenticated/cursos': typeof AuthenticatedCursosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/minha-trilha': typeof AuthenticatedMinhaTrilhaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/arquivos': typeof AuthenticatedAdminArquivosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/_authenticated/avaliacao/$assessmentId': typeof AuthenticatedAvaliacaoAssessmentIdRoute
  '/_authenticated/curso/$courseId': typeof AuthenticatedCursoCourseIdRoute
  '/_authenticated/admin/acompanhamento/$userId': typeof AuthenticatedAdminAcompanhamentoUserIdRoute
  '/_authenticated/admin/aulas/$lessonId': typeof AuthenticatedAdminAulasLessonIdRoute
  '/_authenticated/admin/avaliacoes/$assessmentId': typeof AuthenticatedAdminAvaliacoesAssessmentIdRoute
  '/_authenticated/admin/cursos/$courseId': typeof AuthenticatedAdminCursosCourseIdRoute
  '/_authenticated/admin/modulos/$moduleId': typeof AuthenticatedAdminModulosModuleIdRoute
  '/_authenticated/admin/acompanhamento/': typeof AuthenticatedAdminAcompanhamentoIndexRoute
  '/_authenticated/admin/aulas/': typeof AuthenticatedAdminAulasIndexRoute
  '/_authenticated/admin/avaliacoes/': typeof AuthenticatedAdminAvaliacoesIndexRoute
  '/_authenticated/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
  '/_authenticated/admin/grupos/': typeof AuthenticatedAdminGruposIndexRoute
  '/_authenticated/admin/modulos/': typeof AuthenticatedAdminModulosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/validar-certificado'
    | '/admin'
    | '/certificados'
    | '/cursos'
    | '/dashboard'
    | '/materiais'
    | '/minha-trilha'
    | '/perfil'
    | '/admin/arquivos'
    | '/admin/usuarios'
    | '/aula/$lessonId'
    | '/avaliacao/$assessmentId'
    | '/curso/$courseId'
    | '/admin/acompanhamento/$userId'
    | '/admin/aulas/$lessonId'
    | '/admin/avaliacoes/$assessmentId'
    | '/admin/cursos/$courseId'
    | '/admin/modulos/$moduleId'
    | '/admin/acompanhamento/'
    | '/admin/aulas/'
    | '/admin/avaliacoes/'
    | '/admin/cursos/'
    | '/admin/grupos/'
    | '/admin/modulos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/validar-certificado'
    | '/admin'
    | '/certificados'
    | '/cursos'
    | '/dashboard'
    | '/materiais'
    | '/minha-trilha'
    | '/perfil'
    | '/admin/arquivos'
    | '/admin/usuarios'
    | '/aula/$lessonId'
    | '/avaliacao/$assessmentId'
    | '/curso/$courseId'
    | '/admin/acompanhamento/$userId'
    | '/admin/aulas/$lessonId'
    | '/admin/avaliacoes/$assessmentId'
    | '/admin/cursos/$courseId'
    | '/admin/modulos/$moduleId'
    | '/admin/acompanhamento'
    | '/admin/aulas'
    | '/admin/avaliacoes'
    | '/admin/cursos'
    | '/admin/grupos'
    | '/admin/modulos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/validar-certificado'
    | '/_authenticated/admin'
    | '/_authenticated/certificados'
    | '/_authenticated/cursos'
    | '/_authenticated/dashboard'
    | '/_authenticated/materiais'
    | '/_authenticated/minha-trilha'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/arquivos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/aula/$lessonId'
    | '/_authenticated/avaliacao/$assessmentId'
    | '/_authenticated/curso/$courseId'
    | '/_authenticated/admin/acompanhamento/$userId'
    | '/_authenticated/admin/aulas/$lessonId'
    | '/_authenticated/admin/avaliacoes/$assessmentId'
    | '/_authenticated/admin/cursos/$courseId'
    | '/_authenticated/admin/modulos/$moduleId'
    | '/_authenticated/admin/acompanhamento/'
    | '/_authenticated/admin/aulas/'
    | '/_authenticated/admin/avaliacoes/'
    | '/_authenticated/admin/cursos/'
    | '/_authenticated/admin/grupos/'
    | '/_authenticated/admin/modulos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ValidarCertificadoRoute: typeof ValidarCertificadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar-certificado': {
      id: '/validar-certificado'
      path: '/validar-certificado'
      fullPath: '/validar-certificado'
      preLoaderRoute: typeof ValidarCertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos': {
      id: '/_authenticated/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof AuthenticatedCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-trilha': {
      id: '/_authenticated/minha-trilha'
      path: '/minha-trilha'
      fullPath: '/minha-trilha'
      preLoaderRoute: typeof AuthenticatedMinhaTrilhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/arquivos': {
      id: '/_authenticated/admin/arquivos'
      path: '/arquivos'
      fullPath: '/admin/arquivos'
      preLoaderRoute: typeof AuthenticatedAdminArquivosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/aula/$lessonId': {
      id: '/_authenticated/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/aula/$lessonId'
      preLoaderRoute: typeof AuthenticatedAulaLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacao/$assessmentId': {
      id: '/_authenticated/avaliacao/$assessmentId'
      path: '/avaliacao/$assessmentId'
      fullPath: '/avaliacao/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAvaliacaoAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/$courseId': {
      id: '/_authenticated/curso/$courseId'
      path: '/curso/$courseId'
      fullPath: '/curso/$courseId'
      preLoaderRoute: typeof AuthenticatedCursoCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/acompanhamento/': {
      id: '/_authenticated/admin/acompanhamento/'
      path: '/acompanhamento'
      fullPath: '/admin/acompanhamento/'
      preLoaderRoute: typeof AuthenticatedAdminAcompanhamentoIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/acompanhamento/$userId': {
      id: '/_authenticated/admin/acompanhamento/$userId'
      path: '/acompanhamento/$userId'
      fullPath: '/admin/acompanhamento/$userId'
      preLoaderRoute: typeof AuthenticatedAdminAcompanhamentoUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/aulas/': {
      id: '/_authenticated/admin/aulas/'
      path: '/aulas'
      fullPath: '/admin/aulas/'
      preLoaderRoute: typeof AuthenticatedAdminAulasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/aulas/$lessonId': {
      id: '/_authenticated/admin/aulas/$lessonId'
      path: '/aulas/$lessonId'
      fullPath: '/admin/aulas/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminAulasLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/avaliacoes/': {
      id: '/_authenticated/admin/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes/'
      preLoaderRoute: typeof AuthenticatedAdminAvaliacoesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/avaliacoes/$assessmentId': {
      id: '/_authenticated/admin/avaliacoes/$assessmentId'
      path: '/avaliacoes/$assessmentId'
      fullPath: '/admin/avaliacoes/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAdminAvaliacoesAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cursos/': {
      id: '/_authenticated/admin/cursos/'
      path: '/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AuthenticatedAdminCursosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cursos/$courseId': {
      id: '/_authenticated/admin/cursos/$courseId'
      path: '/cursos/$courseId'
      fullPath: '/admin/cursos/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCursosCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/grupos/': {
      id: '/_authenticated/admin/grupos/'
      path: '/grupos'
      fullPath: '/admin/grupos/'
      preLoaderRoute: typeof AuthenticatedAdminGruposIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modulos/': {
      id: '/_authenticated/admin/modulos/'
      path: '/modulos'
      fullPath: '/admin/modulos/'
      preLoaderRoute: typeof AuthenticatedAdminModulosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modulos/$moduleId': {
      id: '/_authenticated/admin/modulos/$moduleId'
      path: '/modulos/$moduleId'
      fullPath: '/admin/modulos/$moduleId'
      preLoaderRoute: typeof AuthenticatedAdminModulosModuleIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminArquivosRoute: typeof AuthenticatedAdminArquivosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminAcompanhamentoUserIdRoute: typeof AuthenticatedAdminAcompanhamentoUserIdRoute
  AuthenticatedAdminAulasLessonIdRoute: typeof AuthenticatedAdminAulasLessonIdRoute
  AuthenticatedAdminAvaliacoesAssessmentIdRoute: typeof AuthenticatedAdminAvaliacoesAssessmentIdRoute
  AuthenticatedAdminCursosCourseIdRoute: typeof AuthenticatedAdminCursosCourseIdRoute
  AuthenticatedAdminModulosModuleIdRoute: typeof AuthenticatedAdminModulosModuleIdRoute
  AuthenticatedAdminAcompanhamentoIndexRoute: typeof AuthenticatedAdminAcompanhamentoIndexRoute
  AuthenticatedAdminAulasIndexRoute: typeof AuthenticatedAdminAulasIndexRoute
  AuthenticatedAdminAvaliacoesIndexRoute: typeof AuthenticatedAdminAvaliacoesIndexRoute
  AuthenticatedAdminCursosIndexRoute: typeof AuthenticatedAdminCursosIndexRoute
  AuthenticatedAdminGruposIndexRoute: typeof AuthenticatedAdminGruposIndexRoute
  AuthenticatedAdminModulosIndexRoute: typeof AuthenticatedAdminModulosIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminArquivosRoute: AuthenticatedAdminArquivosRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminAcompanhamentoUserIdRoute:
      AuthenticatedAdminAcompanhamentoUserIdRoute,
    AuthenticatedAdminAulasLessonIdRoute: AuthenticatedAdminAulasLessonIdRoute,
    AuthenticatedAdminAvaliacoesAssessmentIdRoute:
      AuthenticatedAdminAvaliacoesAssessmentIdRoute,
    AuthenticatedAdminCursosCourseIdRoute:
      AuthenticatedAdminCursosCourseIdRoute,
    AuthenticatedAdminModulosModuleIdRoute:
      AuthenticatedAdminModulosModuleIdRoute,
    AuthenticatedAdminAcompanhamentoIndexRoute:
      AuthenticatedAdminAcompanhamentoIndexRoute,
    AuthenticatedAdminAulasIndexRoute: AuthenticatedAdminAulasIndexRoute,
    AuthenticatedAdminAvaliacoesIndexRoute:
      AuthenticatedAdminAvaliacoesIndexRoute,
    AuthenticatedAdminCursosIndexRoute: AuthenticatedAdminCursosIndexRoute,
    AuthenticatedAdminGruposIndexRoute: AuthenticatedAdminGruposIndexRoute,
    AuthenticatedAdminModulosIndexRoute: AuthenticatedAdminModulosIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRoute
  AuthenticatedCursosRoute: typeof AuthenticatedCursosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedMinhaTrilhaRoute: typeof AuthenticatedMinhaTrilhaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAulaLessonIdRoute: typeof AuthenticatedAulaLessonIdRoute
  AuthenticatedAvaliacaoAssessmentIdRoute: typeof AuthenticatedAvaliacaoAssessmentIdRoute
  AuthenticatedCursoCourseIdRoute: typeof AuthenticatedCursoCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRoute,
  AuthenticatedCursosRoute: AuthenticatedCursosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedMinhaTrilhaRoute: AuthenticatedMinhaTrilhaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAulaLessonIdRoute: AuthenticatedAulaLessonIdRoute,
  AuthenticatedAvaliacaoAssessmentIdRoute:
    AuthenticatedAvaliacaoAssessmentIdRoute,
  AuthenticatedCursoCourseIdRoute: AuthenticatedCursoCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ValidarCertificadoRoute: ValidarCertificadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
